spring:
  application:
    name: vendor
  datasource:
    url: jdbc:postgresql://localhost:54320/vendor_db?useTimezone=true
    username: root
    password: vend123
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false  # Para garantir suporte a rollback

  jpa:
    hibernate:
      ddl-auto: none
      jdbc.time_zone: UTC
    show-sql: true
    format_sql: true

  flyway:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "metrics"
